global:
  pullSecrets: []
  imageRegistry: ""
image:
  registry: ghcr.io
  repository: hierynomus/sprouter
  tag: v0.2.0
  pullPolicy: IfNotPresent


serviceAccount:
  enabled: true
  name: sprouter

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

fullnameOverride: ""
nameOverride: ""
