{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sprouter.serviceAccountName" . }}
  labels:
    {{- include "sprouter.labels" . | nindent 4 }}
{{- end -}}
